# Generated by Django 2.1.8 on 2019-04-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_creation', '0003_auto_20190420_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_details',
            name='file',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
