# Generated by Django 2.1.7 on 2019-04-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_creation', '0004_auto_20190420_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_tickets',
            name='read_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
