# Generated by Django 2.1.7 on 2019-04-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_creation', '0005_auto_20190421_2320'),
        ('ticket_creation', '0006_auto_20190421_1746'),
    ]

    operations = [
    ]
